Simulacromvc/Models/Companie.cs
namespace Simulacromvc.Models
{
    public class Companie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nit { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Phone { get; set; }
        public string LegalRepresentative { get; set; }
        public long SectorId { get; set; } // Cambiado a long
        public DateTime? created_at { get; set; }
        public DateTime? updated_at { get; set; }
    }
}

Simulacromvc/Models/ErrorViewModel.cs
namespace Simulacromvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Simulacromvc/Models/Sector.cs
namespace Simulacromvc.Models{
    public class Sector{
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? Author { get; set; }
        public DateTime? created_at { get; set; }
        public DateTime? updated_at { get; set; }


    }

}

Simulacromvc/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Simulacromvc.Controllers;
using Simulacromvc.Models;
using Simulacromvc.Data;
using Simulacromvc.Helpers;
using Simulacromvc.Providers;

namespace Simulacromvc.Controllers{
    public class CompaniesController : Controller{
        public readonly CompanieContext _context;
        private readonly HelperUploadFiles helperUploadFiles;

        public CompaniesController(CompanieContext context, HelperUploadFiles helperUpload)
        {
            _context = context;
            this.helperUploadFiles=helperUpload;
        }
        public async Task<IActionResult> Index(){
            var companies = await _context.Companies.ToListAsync();
            return View(companies);
        }
        public async Task<IActionResult> Details(int? id){
            
            return View(await _context.Companies.FirstOrDefaultAsync(x => x.Id == id));
        }
        public IActionResult Create(){
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Companie companie, IFormFile archivo ,int ubicacion){
            if(ModelState.IsValid){ 
                string nombreArchivo = archivo.FileName;
                string path = "";

                 switch(ubicacion){

                case 0:
                    path = await this.helperUploadFiles.UploadFilesAsync(archivo, nombreArchivo, Folders.Uploads);
                break;
                case 1:
                    path = await this.helperUploadFiles.UploadFilesAsync(archivo, nombreArchivo, Folders.Images);
                break;
                case 2:
                    path = await this.helperUploadFiles.UploadFilesAsync(archivo, nombreArchivo, Folders.Documents);
                break;
                case 3:
                    path = await this.helperUploadFiles.UploadFilesAsync(archivo, nombreArchivo, Folders.Temp);
                break;
               

            }
                if(archivo!= null){
                   
                    companie.Logo = nombreArchivo;
                }
                _context.Companies.Add(companie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(companie);
        }
        public async Task<IActionResult> Edit(int? id){
            return View(await _context.Companies.FirstOrDefaultAsync(x =>x.Id == id));

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Companie companie){
            if(ModelState.IsValid){
                _context.Companies.Update(companie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(companie);
        }
        public async Task<IActionResult> Delete(int id, Companie companie)
        {
        
            _context.Companies.Remove(companie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
           public ActionResult Search(string searchTerm)
{
    var companies = _context.Companies.ToList(); // Obtener todos los sectores

    if (!string.IsNullOrEmpty(searchTerm))
    {
        
        var searchTermLower = searchTerm.ToLower();
        companies = companies.Where(u => u.Name.ToLower().Contains(searchTermLower)).ToList();
    }

    return PartialView("_CompanieList", companies); // Devolver vista parcial con lista de sectores
}
        
        
    }
}

Simulacromvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Simulacromvc.Models;

namespace Simulacromvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Simulacromvc/Controllers/SectorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Simulacromvc.Models;
using Simulacromvc.Data;

namespace Simulacromvc.Controllers{
    public class SectorsController : Controller{

        // Contexto de la base de datos
        public readonly CompanieContext _context;

        // Constructor que recibe el contexto de la base de datos
        public SectorsController(CompanieContext context)
        {
            _context = context;
        }

        // Método para mostrar la lista de sectores
        public async Task<IActionResult> Index(){
            var sectors = await _context.Sectors.ToListAsync();
            return View(sectors);
        }

        // Método para mostrar los detalles de un sector específico
        public async Task<IActionResult> Details(int? id){
            var sector = await _context.Sectors.FindAsync(id);
            return View(sector);
        }

        // Método para mostrar el formulario de creación de un nuevo sector
        public IActionResult Create(){
            return View();
        }

        // Método para procesar la creación de un nuevo sector
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Sector sector){
            if(ModelState.IsValid){
                _context.Sectors.Add(sector);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sector);
        }

        // Método para mostrar el formulario de edición de un sector existente
        public async Task<IActionResult> Edit(int? id){
            var sector = await _context.Sectors.FindAsync(id);
            return View(sector);
        }

        // Método para procesar la edición de un sector existente
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Sector sector){
            if(ModelState.IsValid){
                _context.Sectors.Update(sector);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sector);
        }

        // Método para eliminar un sector
        public async Task<IActionResult> Delete(int id, Sector sector)
        {
            _context.Sectors.Remove(sector);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Método para buscar sectores según un término de búsqueda
        public ActionResult Search(string searchTerm)
        {
            var sectors = _context.Sectors.ToList(); // Obtener todos los sectores

            if (!string.IsNullOrEmpty(searchTerm))
            {
                var searchTermLower = searchTerm.ToLower();
                // Filtrar los sectores cuyo nombre contiene el término de búsqueda
                sectors = sectors.Where(u => u.Name.ToLower().Contains(searchTermLower)).ToList();
            }

            // Devolver vista parcial con lista de sectores
            return PartialView("_SectorList", sectors);
        }
    }
}

Simulacromvc/Views/Companies/Create.cshtml
@model Companie
@{
    ViewData["Title"] = "Home Page";
}

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="agregarLibroModalLabel">Agregar Compañia</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <form asp-action="Create" method="post" enctype="multipart/form-data">

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nit" class="control-label"></label>
                    <input asp-for="Nit" class="form-control" />
                    <span asp-validation-for="Nit" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Logo" class="control-label"></label>
                    <input asp-for="Logo" class="form-control" />
                    <span asp-validation-for="Logo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LegalRepresentative" class="control-label"></label>
                    <input asp-for="LegalRepresentative" class="form-control" />
                    <span asp-validation-for="LegalRepresentative" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SectorId" class="control-label"></label>
                    <input asp-for="SectorId" class="form-control" />
                    <span asp-validation-for="SectorId" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label for="">Ubicacion:</label>
                        <select name="ubicacion" id="" class="form-select">
                            <option value="1">Imagenes</option>
                            <option value="2">Documentos</option>
                            <option value="0">Descargas</option>
                            <option value="3">Temporal</option>
                        </select>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Logo"></label>
                            <input type="file" name="archivo" class="form-control">
                        </div>

                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="created_at" class="control-label"></label>
                    <input asp-for="created_at" class="form-control" />
                    <span asp-validation-for="created_at" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="updated_at" class="control-label"></label>
                    <input asp-for="updated_at" class="form-control" />
                    <span asp-validation-for="updated_at" class="text-danger"></span>
                </div>
                <button>Guardar</button>
            </form>
        </div>
    </div>
</div>
</div>
</div>

Simulacromvc/Views/Companies/Details.cshtml
@* @model Companie
@{
    ViewData["Title"] = "Home Page";
}

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="detallesProductoModalLabel">Detalles del Usuario</h5>
           <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="window.location.href='/Companies'"></button>

        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-8">
                    <p><strong>Id:</strong>@Model.Id</p>
                    <p><strong>Nombre:</strong>@Model.Name</p>
                    <p><strong>Nit:</strong>@Model.Nit</p>
                    <p><strong>Direccion:</strong>@Model.Address</p>
                    <p><strong>Descripcion:</strong>@Model.Description</p>
                    <p><strong>Logo:</strong><img src="@Model.Logo" alt="Company Logo" style="max-width: 100px; max-height: 100px;" /></p>
                    <p><strong>Telefono:</strong>@Model.Phone</p>
                    <p><strong>Representante Legal:</strong>@Model.LegalRepresentative</p>
                    <p><strong>SectorId:</strong>@Model.SectorId</p>
                    <p><strong>created_at:</strong>@Model.created_at</p>
                    <p><strong>updated_at:</strong>@Model.updated_at</p>
                </div>
            </div>
        </div>
    </div>
</div>

 *@

Simulacromvc/Views/Companies/Edit.cshtml
@model Companie
@{
    ViewData["Title"] = "Home Page";
}

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="agregarLibroModalLabel">Editar</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <form asp-action="Edit" asp-controller="Companies" asp-route-id="@Model.Id" method="post">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" value="@Model.Name">
                </div>
                <div class="form-group">
                    <label asp-for="Nit" class="control-label"></label>
                    <input asp-for="Nit" class="form-control" value="@Model.Nit">
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" value="@Model.Address">
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" value="@Model.Description">
                </div>
                <div class="form-group">
                    <label asp-for="Logo" class="control-label"></label>
                    <input asp-for="Logo" class="form-control" value="@Model.Logo">
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" value="@Model.Phone">
                </div>
                <div class="form-group">
                    <label asp-for="LegalRepresentative" class="control-label"></label>
                    <input asp-for="LegalRepresentative" class="form-control" value="@Model.LegalRepresentative">
                </div>
                <div class="form-group">
                    <label asp-for="SectorId" class="control-label"></label>
                    <input asp-for="SectorId" class="form-control" value="@Model.SectorId">
                </div>
                <div class="form-group">
                    <label asp-for="created_at" class="control-label"></label>
                    <input asp-for="created_at" class="form-control" value="@Model.created_at">
                </div>
                <div class="form-group">
                    <label asp-for="updated_at" class="control-label"></label>
                    <input asp-for="updated_at" class="form-control" value="@Model.updated_at">
                </div>
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </form>
        </div>
    </div>
</div>
                  
            

Simulacromvc/Views/Companies/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="content-page">
        <div class="content">
            <div class="container-fluid mt-4">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <a asp-controller="Companies" asp-action="Create" class="btn btn-primary mb-3">Crear
                                    Compañia</a>
                                <h2>Compañias</h2>
                                <form id="searchForm">
                                    <input type="text" id="searchInput" placeholder="Buscar por nombre...">
                                    <input type="submit" value="Buscar">
                                </form>
                                <div id="companiList">
                                    
                                </div>
                                <div class="table-responsive mt-4">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <tr class="bg-secondary text-white">
                                                <th>#</th>
                                                <th>Name</th>
                                                <th>Nit</th>
                                                <th>Address</th>
                                                <th>Description</th>
                                                <th>Logo</th>
                                                <th>Phone</th>
                                                <th>LegalRepresentative</th>
                                                <th>SectorId</th>
                                                <th>created_at</th>
                                                <th>updated_at</th>
                                                <th>Action</th>
                                            </tr>

                                        </thead>

                                        @foreach (var companie in Model)
                                        {
                                            <tr>
                                                <th scope="row">@companie.Id</th>
                                                <td>@companie.Name</td>
                                                <td>@companie.Nit</td>
                                                <td>@companie.Address</td>
                                                <td>@companie.Description</td>
                                                <td><img src="~/images/@companie.Logo" alt="@companie.Logo"
                                                        style="max-width: 100px; max-height: 100px;" /></td>
                                                <td>@companie.Phone</td>
                                                <td>@companie.LegalRepresentative</td>
                                                <td>@companie.SectorId</td>
                                                <td>@companie.created_at</td>
                                                <td>@companie.updated_at</td>
                                                <td>
                                                    <a asp-controller="Companies" asp-action="Details"
                                                        asp-route-id="@companie.Id" class="btn btn-primary">Details</a>
                                                    <a asp-controller="Companies" asp-action="Edit"
                                                        asp-route-id="@companie.Id" class="btn btn-warning">Edit</a>
                                                   <a asp-action="Delete" asp-route-id="@companie.Id" class="btn btn-danger">Eliminar</a>

                                                </td>
                                            </tr>
                                        }
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  @section Scripts {
    <script>
        var searchUrl = '@Url.Action("Search", "Companies")'; 
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/js/searchCm.js"></script>
}
</body>

</html>

Simulacromvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Simulacromvc/Views/Sectors/Edit.cshtml
@model Sector
@{
    ViewData["Title"] = "Home Page";
}

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="agregarLibroModalLabel">Editar</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <form asp-action="Edit" asp-controller="Sectors" asp-route-id="@Model.Id" method="post">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" value="@Model.Name">
                </div>
              
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" value="@Model.Description">
                </div>
                <div class="form-group">
                    <label asp-for="Author" class="control-label"></label>
                    <input asp-for="Author" class="form-control" value="@Model.Author">
                </div>
                <div class="form-group">
                    <label asp-for="created_at" class="control-label"></label>
                    <input asp-for="created_at" class="form-control" value="@Model.created_at">
                </div>
                <div class="form-group">
                    <label asp-for="updated_at" class="control-label"></label>
                    <input asp-for="updated_at" class="form-control" value="@Model.updated_at">
                </div>
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </form>
        </div>
    </div>
</div>
                  
            

Simulacromvc/Views/Sectors/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="content-page">
        <div class="content">
            <div class="container-fluid mt-4">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <a asp-controller="Sectors" asp-action="Create" class="btn btn-primary mb-3">Crear
                                    Sector</a>
                                <h2>Sectores</h2>
                                <form id="searchForm">
                                    <input type="text" id="searchInput" placeholder="Buscar por nombre...">
                                    <input type="submit" value="Buscar">
                                </form>
                                <div id="sectorList">
                                  
                                </div>
                                <div class="table-responsive mt-4">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <tr class="bg-secondary text-white">
                                                <th>#</th>
                                                <th>Nombre</th>
                                                <th>Descripcion</th>
                                                <th>Autor</th>
                                                <th>created_at</th>
                                                <th>updated_at</th>
                                                <th>Action</th>
                                            </tr>

                                        </thead>

                                        @foreach (var sector in Model)
                                        {
                                            <tr>
                                                <th scope="row">@sector.Id</th>
                                                <td>@sector.Name</td>
                                                <td>@sector.Description</td>
                                                <td>@sector.Author</td>
                                                <td>@sector.created_at</td>
                                                <td>@sector.updated_at</td>
                                                
                                                <td>
                                                    <a asp-controller="Sectors" asp-action="Details"
                                                        asp-route-id="@sector.Id" class="btn btn-primary">Details</a>
                                                    <a asp-controller="Sectors" asp-action="Edit"
                                                        asp-route-id="@sector.Id" class="btn btn-warning">Edit</a>
                                                   <a asp-action="Delete" asp-route-id="@sector.Id" class="btn btn-danger">Eliminar</a>

                                                </td>
                                            </tr>
                                        }
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
           @section Scripts {
    <script>
        var searchUrl = '@Url.Action("Search", "Sectors")'; 
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/js/searchCm.js"></script>
}

</body>

</html>

Simulacromvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Simulacromvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Simulacromvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Simulacromvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Compañias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sectors" asp-action="Index">Sectores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Simulacromvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>